[package]
name = "burp-rust-lib"
version = "0.1.0"
authors = ["Peter Halliday <pghalliday@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.71"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.47"
once_cell = "1.18.0"
